name: Deploy homestuck.net Static Site

on:
  push:
    branches: [master]

jobs:
  deploy-static:
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest code on server
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.SERVER_PORT }}
            script: |
                set -euo pipefail
                cd "${{ secrets.EXPORT_DIR }}"
                # stash any uncommitted or untracked changes
                git stash push --include-untracked -m "auto-deploy-stash" || true
                # fetch & fast-forward to master
                git fetch origin master
                git reset --hard origin/master
                # reapply stash if needed
                git stash pop || true
